language: go

go:
  - 1.8

install:
  - go get ./...
  - go get github.com/gordonklaus/ineffassign
  - go get github.com/client9/misspell/cmd/misspell

script:
  - diff <(echo -n) <(gofmt -s -d .)
  - go vet -race ./...
  - ineffassign .
  - misspell -error .
