language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

install:
  - go get ./...
  - go get github.com/gordonklaus/ineffassign
  - go get github.com/client9/misspell/cmd/misspell
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - gometalinter  --disable-all -E vet -E gofmt -E misspell -E ineffassign -E deadcode -E gosimple -E varcheck -E structcheck -E unused --tests --vendor ./...
